### ISSUE TITLE
Uploading .fasta file

### ISSUE THREAD

**Issue by cjmiller1622** [bioneos/genetics-demo-javafx#3]
Add a button to the fxml that allows a user to upload a .fasta file of their choice for determining its corresponding mRNA and protein sequences.

**Comment by Wheelspawn** [comment]
Right now the user cannot choose to upload .fasta as mRNA or protein sequence. It uploads to the protein field by default.

**Comment by dominicrutk** [comment]
Project moved to [new location](https://github.com/bioneos/genetics-demo/tree/devel/standalone/javafx)
