### ISSUE TITLE
Global Alignment

### ISSUE THREAD

**Issue by cjmiller1622** [bioneos/genetics-demo-javafx#6]
**Protein sequence alignment**
*Use Needleman-Wunsch*
Calculate the global alignment score of two given protein sequences. You can use whichever scores you feel are appropriate for matches, mismatches, and gap scores. (Typically use -2 for a gap, -1 for mismatch, and +2 for a match). 

Output score.

**Comment by dominicrutk** [comment]
Project moved to [new location](https://github.com/bioneos/genetics-demo/tree/devel/standalone/javafx)
